### ISSUE TITLE
Ваш аккаунт не подходит для авторизации через социальную сеть (Yandex) с почтой (yandex.ru).

### ISSUE THREAD

**Issue by PrimechaevRuslan** [playa-ru/keycloak-russian-providers#44]
### Подключил VK, все работает нормально. С Yandex и Mail.RU вот такая проблема.
**Версия Keycloak - 25.0.2**
Жму Login у себя на сайте -> кидает на кк -> жму Yandex в поле "or sign with" -> Кидает на яндекс, загрузка 2-3 секунды -> кидает обратно на кк с ошибкой.
![image](https://github.com/user-attachments/assets/753bee09-382d-47d9-810e-026177570592)
**Логи консоль ->** 
Failed to load resource: the server responded with a status of 502 ()
**Логи докер ->**
```
2024-09-03 07:54:41,507 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-7) Failed to make identity provider oauth callback: java.lang.IllegalArgumentException: Ваш аккаунт не подходит для авторизации через социальную сеть (Yandex) с почтой (yandex.ru).
        at ru.playa.keycloak.modules.Utils.isHostedDomain(Utils.java:64)
        at ru.playa.keycloak.modules.yandex.YandexIdentityProvider.extractIdentityFromProfile(YandexIdentityProvider.java:83)
        at ru.playa.keycloak.modules.yandex.YandexIdentityProvider.doGetFederatedIdentity(YandexIdentityProvider.java:107)
        at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.getFederatedIdentity(AbstractOAuth2IdentityProvider.java:314)
        at ru.playa.keycloak.modules.AbstractRussianEndpoint.authResponse(AbstractRussianEndpoint.java:165)
        at ru.playa.keycloak.modules.AbstractRussianEndpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-09-03 07:54:41,508 WARN  [org.keycloak.events] (executor-thread-7) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="***", realmName="***", clientId="***", userId="null", ipAddress="***.***.***.***", error="identity_provider_login_failure", code_id="***"
```

**Comment by onotoliy** [comment]
Добрый день. Покажите, пожалуйста, настройки HostedDomain.

**Comment by PrimechaevRuslan** [comment]
Добрый, после вашего сообщения понял свою ошибку, спасибо :)
