### ISSUE TITLE
Ошибка при входе через VK ID

### ISSUE THREAD

**Issue by azazuent** [playa-ru/keycloak-russian-providers#51]
### Steps to reproduce
**Keycloak** 26.0.7
**keycloak-russian-providers**: https://nexus.playa.ru/nexus/repository/releases/ru/playa/keycloak/keycloak-russian-providers/1.0.28/keycloak-russian-providers-1.0.28.jar
Настройка VK приложения соответственно https://github.com/playa-ru/keycloak-russian-providers/blob/master/docs/vk.md
Метод установки: 
### compose.yml
```
services:
  keycloak:
    ...
    volumes:
      - ./keycloak/keycloak-russian-providers-1.0.28.jar:/opt/keycloak/providers/keycloak-russian-providers-1.0.28.jar:ro
```
### Expected behaviour
Переход в соответствующее приложение после входа через VK ID 
### Actual behaviour
Internal server error
### Operating system
Ubuntu 22.04 LTS
### Logs
```
2024-12-13 10:15:00,530 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-10) Uncaught server error: java.lang.NoClassDefFoundError: javax/ws/rs/WebApplicationException
        at ru.playa.keycloak.modules.AbstractRussianOAuth2IdentityProvider.callback(AbstractRussianOAuth2IdentityProvider.java:44)
        at org.keycloak.services.resources.IdentityBrokerService.getEndpoint(IdentityBrokerService.java:445)
        at org.keycloak.services.resources.IdentityBrokerService$quarkusrestinvoker$getEndpoint_106b3afe16881212afc5cdb68385f5f8615e233e.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.WebApplicationException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:114)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:72)
        ... 14 more
```

**Comment by onotoliy** [comment]
Hi. For Keycloak 26.0.7, use the provider version. [26.0.0.rsp](https://mvnrepository.com/artifact/ru.playa.keycloak/keycloak-russian-providers/26.0.0.rsp)

**Comment by azazuent** [comment]
Спасибо!
